In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

Matplotlib is building the font cache; this may take a moment.


In [5]:
from sklearn.datasets import make_classification

In [8]:
X,y=make_classification(n_samples=1000,n_classes=2,n_features=10,random_state=42)

In [9]:
X.shape

(1000, 10)

In [1]:
from sklearn.model_selection import train_test_split

In [11]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=42)

In [12]:
X_train

array([[-1.01232181,  0.28123049, -0.87512274, ...,  1.15469377,
         1.18259881, -1.27036205],
       [-0.02101069,  0.74744497, -0.03870931, ..., -0.10435845,
        -0.04258589,  0.45015563],
       [ 0.37607013,  0.33385997,  0.24958079, ..., -1.31221919,
        -0.68607663,  1.08176673],
       ...,
       [ 0.04091467,  0.42796263, -0.00235298, ..., -1.92277177,
        -0.17104772,  1.63925652],
       [ 0.3393792 , -0.64015446,  0.25253995, ..., -1.39922826,
        -0.52991248, -0.7348109 ],
       [ 1.84815207, -0.31305803,  1.78069642, ...,  0.60451533,
        -1.56102804, -1.25040773]])

In [13]:
from sklearn.linear_model import LogisticRegression
logistic=LogisticRegression()

In [14]:
logistic.fit(X_train,y_train)

LogisticRegression()

In [15]:
y_pred=logistic.predict(X_test)

In [16]:
y_pred

array([0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0,
       0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 0])

In [17]:
logistic.predict_proba(X_test)

array([[7.80405311e-01, 2.19594689e-01],
       [3.33970550e-02, 9.66602945e-01],
       [6.54302432e-01, 3.45697568e-01],
       [7.74617238e-02, 9.22538276e-01],
       [9.74933382e-01, 2.50666180e-02],
       [4.02908279e-02, 9.59709172e-01],
       [9.77942561e-01, 2.20574386e-02],
       [9.53537697e-01, 4.64623026e-02],
       [7.96199363e-01, 2.03800637e-01],
       [6.82684766e-01, 3.17315234e-01],
       [9.11092664e-01, 8.89073362e-02],
       [2.49231213e-01, 7.50768787e-01],
       [5.20874896e-01, 4.79125104e-01],
       [2.11316593e-01, 7.88683407e-01],
       [7.85894005e-01, 2.14105995e-01],
       [9.43617675e-01, 5.63823254e-02],
       [2.64794983e-02, 9.73520502e-01],
       [3.45032612e-01, 6.54967388e-01],
       [3.19896268e-01, 6.80103732e-01],
       [2.00610368e-01, 7.99389632e-01],
       [4.95913661e-01, 5.04086339e-01],
       [9.62346032e-01, 3.76539681e-02],
       [1.92460673e-01, 8.07539327e-01],
       [7.86737166e-01, 2.13262834e-01],
       [8.671825

In [18]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [21]:
score=accuracy_score(y_test,y_pred)
print(score)

0.84


In [22]:
confusion_matrix(y_test,y_pred)

array([[ 98,  15],
       [ 25, 112]], dtype=int64)

In [24]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.80      0.87      0.83       113
           1       0.88      0.82      0.85       137

    accuracy                           0.84       250
   macro avg       0.84      0.84      0.84       250
weighted avg       0.84      0.84      0.84       250

